import type { PairCommandSpec } from "./types";

const NMEA_TYPE_OPTIONS = [
  { value: "-1", label: "All sentences (-1)" },
  { value: "0", label: "GGA (0)" },
  { value: "1", label: "GLL (1)" },
  { value: "2", label: "GSA (2)" },
  { value: "3", label: "GSV (3)" },
  { value: "4", label: "RMC (4)" },
  { value: "5", label: "VTG (5)" },
  { value: "6", label: "ZDA (6)" },
];

export const PAIR_COMMANDS: PairCommandSpec[] = [
  {
    cid: "002",
    name: "Restart GNSS",
    category: "Restart",
    description: "停止していた GNSS 測位を再開",
    args: [],
    resultKind: "ack-only",
  },
  {
    cid: "003",
    name: "Stop GNSS",
    category: "Restart",
    description: "GNSS 測位を一時停止 (NMEA 出力が止まる)",
    args: [],
    resultKind: "ack-only",
  },
  {
    cid: "004",
    name: "Hot Start",
    category: "Restart",
    description: "NVRAM 保存のエフェメリスを使用して再起動",
    args: [],
    resultKind: "ack-only",
    destructive: true,
  },
  {
    cid: "005",
    name: "Warm Start",
    category: "Restart",
    description: "エフェメリスを使用しない再起動",
    args: [],
    resultKind: "ack-only",
    destructive: true,
  },
  {
    cid: "006",
    name: "Cold Start",
    category: "Restart",
    description: "アルマナック・エフェメリスなしで再起動",
    args: [],
    resultKind: "ack-only",
    destructive: true,
  },
  {
    cid: "007",
    name: "Full Cold Start",
    category: "Restart",
    description: "工場出荷状態に戻して再起動",
    args: [],
    resultKind: "ack-only",
    destructive: true,
  },
  {
    cid: "050",
    name: "Set Fix Rate",
    category: "Position",
    description: "FIX 更新周期 (ms) を設定 (100–10000)",
    args: [{ name: "time_ms", kind: { type: "int", min: 100, max: 10000, default: 1000, unit: "ms" } }],
    resultKind: "ack-only",
  },
  {
    cid: "051",
    name: "Get Fix Rate",
    category: "Position",
    description: "FIX 更新周期を問合せ",
    args: [],
    resultKind: "ack-and-followup",
    followUpCid: "051",
    parseFollowUp: (fields) => ({ rateMs: Number(fields[0] ?? 0) }),
  },
  {
    cid: "058",
    name: "Set SNR Threshold",
    category: "Position",
    description: "測位に使用する最小 SNR 値 (9–37, 初期 9)",
    args: [{ name: "min_snr", kind: { type: "int", min: 9, max: 37, default: 9 } }],
    resultKind: "ack-only",
  },
  {
    cid: "059",
    name: "Get SNR Threshold",
    category: "Position",
    description: "最小 SNR 値を問合せ",
    args: [],
    resultKind: "ack-and-followup",
    followUpCid: "059",
    parseFollowUp: (fields) => ({ minSnr: Number(fields[0] ?? 0) }),
  },
  {
    cid: "060",
    name: "Set DR Limit",
    category: "Position",
    description: "推測航法の最大回数 (0–500)。0 で無効",
    args: [{ name: "dr_limit", kind: { type: "int", min: 0, max: 500, default: 0 } }],
    resultKind: "ack-only",
  },
  {
    cid: "061",
    name: "Get DR Limit",
    category: "Position",
    description: "推測航法回数を問合せ",
    args: [],
    resultKind: "ack-and-followup",
    followUpCid: "061",
    parseFollowUp: (fields) => ({ drLimit: Number(fields[0] ?? 0) }),
  },
  {
    cid: "062",
    name: "Set NMEA Output Rate",
    category: "NMEA",
    description: "センテンス毎の出力間隔 (0–20, 0=出力しない)。Type=-1 で全リセット",
    args: [
      { name: "type", kind: { type: "enum", options: NMEA_TYPE_OPTIONS, default: "0" } },
      { name: "rate", kind: { type: "int", min: 0, max: 20, default: 1 } },
    ],
    resultKind: "ack-only",
  },
  {
    cid: "063",
    name: "Get NMEA Output Rate",
    category: "NMEA",
    description: "NMEA 出力間隔を問合せ",
    args: [{ name: "type", kind: { type: "enum", options: NMEA_TYPE_OPTIONS, default: "-1" } }],
    resultKind: "ack-and-followup",
    followUpCid: "063",
    parseFollowUp: (fields) => ({ type: fields[0] ?? "", rate: Number(fields[1] ?? 0) }),
  },
  {
    cid: "066",
    name: "Set GNSS Search Mode",
    category: "GNSS",
    description: "GPS/GLONASS/Galileo/BeiDou/QZSS/NavIC を 0/1 で指定",
    args: [
      { name: "GPS", kind: { type: "enum", options: yesNo(), default: "1" } },
      { name: "GLONASS", kind: { type: "enum", options: yesNo(), default: "1" } },
      { name: "Galileo", kind: { type: "enum", options: yesNo(), default: "1" } },
      { name: "BeiDou", kind: { type: "enum", options: yesNo(), default: "1" } },
      { name: "QZSS", kind: { type: "enum", options: yesNo(), default: "1" } },
      { name: "NavIC", kind: { type: "enum", options: yesNo(), default: "0" } },
    ],
    resultKind: "ack-only",
  },
  {
    cid: "067",
    name: "Get GNSS Search Mode",
    category: "GNSS",
    description: "GNSS サーチモードを問合せ",
    args: [],
    resultKind: "ack-and-followup",
    followUpCid: "067",
    parseFollowUp: (fields) => ({
      GPS: fields[0],
      GLONASS: fields[1],
      Galileo: fields[2],
      BeiDou: fields[3],
      QZSS: fields[4],
      NavIC: fields[5],
    }),
  },
  {
    cid: "068",
    name: "Set HDOP Threshold",
    category: "Position",
    description: "HDOP 閾値。0=無効、それ以外は >= 0.1",
    args: [{ name: "hdop", kind: { type: "float", min: 0, max: 100, step: 0.1, default: 0 } }],
    resultKind: "ack-only",
  },
  {
    cid: "069",
    name: "Get HDOP Threshold",
    category: "Position",
    description: "HDOP 閾値を問合せ",
    args: [],
    resultKind: "ack-and-followup",
    followUpCid: "069",
    parseFollowUp: (fields) => ({ hdop: Number(fields[0] ?? 0) }),
  },
  {
    cid: "070",
    name: "Set Static Threshold",
    category: "Position",
    description: "静止判定の速度閾値 (0–20 dm/s)。0 で無効",
    args: [{ name: "speed_dm_s", kind: { type: "int", min: 0, max: 20, default: 0, unit: "dm/s" } }],
    resultKind: "ack-only",
  },
  {
    cid: "071",
    name: "Get Static Threshold",
    category: "Position",
    description: "静止速度閾値を問合せ",
    args: [],
    resultKind: "ack-and-followup",
    followUpCid: "071",
    parseFollowUp: (fields) => ({ speedMs: Number(fields[0] ?? 0) }),
  },
  {
    cid: "072",
    name: "Set Elevation Mask",
    category: "Position",
    description: "衛星仰角閾値 (-90–90, 初期 5)",
    args: [{ name: "degrees", kind: { type: "int", min: -90, max: 90, default: 5, unit: "°" } }],
    resultKind: "ack-only",
  },
  {
    cid: "073",
    name: "Get Elevation Mask",
    category: "Position",
    description: "仰角閾値を問合せ",
    args: [],
    resultKind: "ack-and-followup",
    followUpCid: "073",
    parseFollowUp: (fields) => ({ degrees: Number(fields[0] ?? 0) }),
  },
  {
    cid: "076",
    name: "Set Datum",
    category: "Position",
    description: "測地系の設定",
    args: [
      {
        name: "datum",
        kind: {
          type: "enum",
          options: [
            { value: "0", label: "WGS84 (0)" },
            { value: "1", label: "TOKYO-M (1)" },
            { value: "2", label: "TOKYO-A (2)" },
          ],
          default: "0",
        },
      },
    ],
    resultKind: "ack-only",
  },
  {
    cid: "077",
    name: "Get Datum",
    category: "Position",
    description: "測地系の問合せ",
    args: [],
    resultKind: "ack-and-followup",
    followUpCid: "077",
    parseFollowUp: (fields) => ({ datum: fields[0] ?? null }),
  },
  {
    cid: "092",
    name: "Set Static Mode",
    category: "Position",
    description: "静止モードの有効/無効",
    args: [{ name: "enable", kind: { type: "enum", options: yesNo(), default: "0" } }],
    resultKind: "ack-only",
  },
  {
    cid: "093",
    name: "Get Static Mode",
    category: "Position",
    description: "静止モードの問合せ",
    args: [],
    resultKind: "ack-and-followup",
    followUpCid: "093",
    parseFollowUp: (fields) => ({ enabled: fields[0] === "1" }),
  },
  {
    cid: "400",
    name: "Set DGPS Source",
    category: "DGPS",
    description: "DGPS 補正ソース",
    args: [
      {
        name: "mode",
        kind: {
          type: "enum",
          options: [
            { value: "0", label: "なし (0)" },
            { value: "1", label: "RTCM (1)" },
            { value: "2", label: "SBAS (2)" },
            { value: "3", label: "SLAS (3)" },
          ],
          default: "0",
        },
      },
    ],
    resultKind: "ack-only",
  },
  {
    cid: "401",
    name: "Get DGPS Source",
    category: "DGPS",
    description: "DGPS 補正ソースの問合せ",
    args: [],
    resultKind: "ack-and-followup",
    followUpCid: "401",
    parseFollowUp: (fields) => ({ mode: fields[0] ?? null }),
  },
  {
    cid: "410",
    name: "Set SBAS",
    category: "DGPS",
    description: "SBAS の有効/無効",
    args: [{ name: "enable", kind: { type: "enum", options: yesNo(), default: "0" } }],
    resultKind: "ack-only",
  },
  {
    cid: "411",
    name: "Get SBAS",
    category: "DGPS",
    description: "SBAS の問合せ",
    args: [],
    resultKind: "ack-and-followup",
    followUpCid: "411",
    parseFollowUp: (fields) => ({ enabled: fields[0] === "1" }),
  },
  {
    cid: "420",
    name: "Set QZSS SLAS",
    category: "DGPS",
    description: "QZSS SLAS の有効/無効",
    args: [{ name: "enable", kind: { type: "enum", options: yesNo(), default: "0" } }],
    resultKind: "ack-only",
  },
  {
    cid: "421",
    name: "Get QZSS SLAS",
    category: "DGPS",
    description: "QZSS SLAS の問合せ",
    args: [],
    resultKind: "ack-and-followup",
    followUpCid: "421",
    parseFollowUp: (fields) => ({ enabled: fields[0] === "1" }),
  },
  {
    cid: "513",
    name: "Save NVRAM to Flash",
    category: "Storage",
    description: "現在の設定を NVRAM (Flash) へ保存。1Hz でのみ有効",
    args: [],
    resultKind: "ack-only",
    destructive: true,
    defaultTimeoutMs: 5000,
  },
  {
    cid: "864",
    name: "Set Baud Rate",
    category: "Port",
    description: "UART ボーレート設定。再起動後に適用",
    args: [
      { name: "port_type", kind: { type: "enum", options: [{ value: "0", label: "UART (0)" }], default: "0" } },
      {
        name: "port_index",
        kind: {
          type: "enum",
          options: [
            { value: "0", label: "UART0 (M02U)" },
            { value: "1", label: "UART1" },
            { value: "2", label: "UART2" },
          ],
          default: "0",
        },
      },
      {
        name: "baud_rate",
        kind: {
          type: "enum",
          options: [
            { value: "4800", label: "4800" },
            { value: "9600", label: "9600" },
            { value: "19200", label: "19200" },
            { value: "38400", label: "38400" },
            { value: "57600", label: "57600" },
            { value: "115200", label: "115200" },
            { value: "230400", label: "230400" },
            { value: "460800", label: "460800" },
            { value: "921600", label: "921600" },
          ],
          default: "115200",
        },
      },
    ],
    resultKind: "ack-only",
    destructive: true,
  },
  {
    cid: "865",
    name: "Get Baud Rate",
    category: "Port",
    description: "ボーレートを問合せ",
    args: [
      { name: "port_type", kind: { type: "enum", options: [{ value: "0", label: "UART (0)" }], default: "0" } },
      {
        name: "port_index",
        kind: {
          type: "enum",
          options: [
            { value: "0", label: "UART0 (M02U)" },
            { value: "1", label: "UART1" },
            { value: "2", label: "UART2" },
          ],
          default: "0",
        },
      },
    ],
    resultKind: "ack-and-followup",
    followUpCid: "865",
    parseFollowUp: (fields) => ({ baudRate: Number(fields[0] ?? 0) }),
  },
];

export const PAIR_CATALOG: Record<string, PairCommandSpec> = Object.fromEntries(
  PAIR_COMMANDS.map((c) => [c.cid, c]),
);

function yesNo() {
  return [
    { value: "0", label: "Disabled (0)" },
    { value: "1", label: "Enabled (1)" },
  ];
}
